.TH libinput-list-quirks "1" "" "libinput @LIBINPUT_VERSION@" "libinput Manual"
.SH NAME
libinput\-list\-quirks \- quirk debug helper for libinput
.SH SYNOPSIS
.B libinput list\-quirks [\-\-data\-dir /path/to/dir] [\-\-verbose\fB] \fI/dev/input/event0\fB
.br
.B libinput list\-quirks [\-\-data\-dir /path/to/dir] [\-\-verbose\fB] \-\-validate\-only
.br
.B libinput list\-quirks [\-\-help]
.SH DESCRIPTION
.PP
The
.B "libinput list\-quirks"
tool parses the quirks file in \fIdata\-dir\fR and prints all quirks applied
to the given device.
.PP
This is a debugging tool only, its output and behavior may change at any
time. Do not rely on the output.
.SH OPTIONS
.TP 8
.B \-\-data\-dir \fI/path/to/dir\fR
Use the given directory as data directory for quirks files.
.TP 8
.B \-\-help
Print help
.TP 8
.B \-\-validate\-only
Only validate that the quirks files can be parsed. When this option is
given, no device file should be supplied.
.TP 8
.B \-\-verbose
Use verbose output, useful for debugging.
.SH LIBINPUT
Part of the
.B libinput(1)
suite
