.TH LIBINPUT "1"
.SH NAME
libinput \- tool to interface with libinput
.SH SYNOPSIS
.B libinput [--help] [--version] <command> [<args>]
.SH DESCRIPTION
.PP
The
.B "libinput"
tool creates a libinput context on the default seat "seat0" and interacts
with that libinput context.
.PP
This tool usually needs to be run as root to have access to the
/dev/input/eventX nodes.
.PP
The context created by this tool is a new libinput context and independent
of that created by the X.Org libinput driver, the Wayland compositor or any
other process that utilizes libinput (henceforth called "the caller").
Configuration options set in this context do not affect any other libinput
contexts.
.PP
Note that a device may be recognized by this tool but not handled by the
X.Org libinput driver or the Wayland compositor.
.SH OPTIONS
.TP 8
.B --help
Print help and exit
.TP 8
.B --version
Print the version and exit

.SH COMMANDS
All commands support a
.B --help
argument that prints command-specific usage
information, e.g.
.B "libinput debug-events --help".
.TP 8
.B libinput-debug-events(1)
Print all events as seen by libinput.
.TP 8
.B libinput-list-devices(1)
List all devices recognized by libinput.
.SH LIBINPUT
Part of the
.B libinput(1)
suite
.PP
.SH SEE ALSO
.PP
libinput(4)
