.TH LIBINPUT-DEBUG-EVENTS "1"
.SH NAME
libinput-debug-events \- debug helper for libinput
.SH SYNOPSIS
.B libinput debug-events [--help] [--show-keycodes]
.SH DESCRIPTION
.PP
The
.B "libinput debug-events"
tool creates a libinput context and prints all events from these devices.
.PP
This is a debugging tool only, its output may change at any time. Do not
rely on the output.
.PP
This tool usually needs to be run as root to have access to the
/dev/input/eventX nodes.
.SH OPTIONS
.TP 8
.B --help
Print help
.TP 8
.B --show-keycodes
Key events shown by this tool are partially obfuscated to avoid passwords
and other sensitive information showing up in the output. Use the
.B --show-keycodes
argument to make all keycodes visible.
.PP
For all other options, see the output from --help. Options may be added or
removed at any time.
.SH NOTES
.PP
Events shown by this tool may not correspond to the events seen by a
different user of libinput. This tool initializes a separate context.
.SH LIBINPUT
Part of the
.B libinput(1)
suite
