.TH LIBINPUT-MEASURE-TRACKPOINT-RANGE "1" "" "libinput @LIBINPUT_VERSION@" "libinput Manual"
.SH NAME
libinput\-measure\-trackpoint\-range \- measure the delta range of a trackpoint
.SH SYNOPSIS
.B libinput measure trackpoint\-range [\-\-help] [/dev/input/event0]
.SH DESCRIPTION
.PP
The
.B "libinput measure trackpoint\-range"
tool measures the delta range of a trackpoint. This is
an interactive tool. When executed, the tool will prompt the user to
interact with the trackpoint. On termination, the tool prints a summary of
the trackpoint deltas seen. This data should be attached to any bug report
relating to the trackpoint's speed.
.PP
This is a debugging tool only, its output may change at any time. Do not
rely on the output.
.PP
This tool usually needs to be run as root to have access to the
/dev/input/eventX nodes.
.SH OPTIONS
If a device node is given, this tool opens that device node. Otherwise, this
tool searches for the first node that looks like a trackpoint and uses that
node.
.TP 8
.B \-\-help
Print help
.SH LIBINPUT
Part of the
.B libinput(1)
suite
