.TH libinput-measure "1" "" "libinput @LIBINPUT_VERSION@" "libinput Manual"
.SH NAME
libinput\-measure \- measure properties of devices
.SH SYNOPSIS
.B libinput measure [\-\-help] \fI<feature> [<args>]\fR
.SH DESCRIPTION
.PP
The
.B "libinput measure"
tool measures properties of one (or more) devices. Depending on what is to
be measured, this too may not create a libinput context.
.PP
This is a debugging tool only, its output may change at any time. Do not
rely on the output.
.PP
This tool usually needs to be run as root to have access to the
/dev/input/eventX nodes.
.SH OPTIONS
.TP 8
.B \-\-help
Print help
.SH FEATURES
Features that can be measured include
.TP 8
.B libinput\-measure\-touchpad\-tap\-time(1)
Measure tap-to-click time
.SH LIBINPUT
Part of the
.B libinput(1)
suite
